FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install pytest

COPY main.py .
COPY test_birthday_api.py .

CMD ["pytest", "-v", "-s", "test_birthday_api.py"]